package com.xh.entity;

import java.util.Date;
//课程评论表
public class T_course_comment {
    //id

    private Integer id;

    //username用户

    private String username;

    //to_username评论对象

    private String toUsername;

    //课程id

    private Integer courseId;

    //章节id

    private Integer sectionId;

    //章节标题

    private String sectionTitle;

    //评论内容

    private String content;

    //创建时间

    private Date createTime;

    //

    @Override
    public String toString() {
        return "T_course_comment{" +
                "id=" + id +
                ", username='" + username + '\'' +
                ", toUsername='" + toUsername + '\'' +
                ", courseId=" + courseId +
                ", sectionId=" + sectionId +
                ", sectionTitle='" + sectionTitle + '\'' +
                ", content='" + content + '\'' +
                ", createTime=" + createTime +
                '}';
    }

    public Integer getId() {
        return id;
    }

    //
    public void setId(Integer id) {
        this.id = id;
    }

    //
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_comment.username
     *
     * @param username the value for t_course_comment.username
     *
     * @mbg.generated Tue Aug 14 20:19:50 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_comment.to_username
     *
     * @return the value of t_course_comment.to_username
     *
     * @mbg.generated Tue Aug 14 20:19:50 CST 2018
     */
    public String getToUsername() {
        return toUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_comment.to_username
     *
     * @param toUsername the value for t_course_comment.to_username
     *
     * @mbg.generated Tue Aug 14 20:19:50 CST 2018
     */
    public void setToUsername(String toUsername) {
        this.toUsername = toUsername == null ? null : toUsername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_comment.course_id
     *
     * @return the value of t_course_comment.course_id
     *
     * @mbg.generated Tue Aug 14 20:19:50 CST 2018
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_comment.course_id
     *
     * @param courseId the value for t_course_comment.course_id
     *
     * @mbg.generated Tue Aug 14 20:19:50 CST 2018
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_comment.section_id
     *
     * @return the value of t_course_comment.section_id
     *
     * @mbg.generated Tue Aug 14 20:19:50 CST 2018
     */
    public Integer getSectionId() {
        return sectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_comment.section_id
     *
     * @param sectionId the value for t_course_comment.section_id
     *
     * @mbg.generated Tue Aug 14 20:19:50 CST 2018
     */
    public void setSectionId(Integer sectionId) {
        this.sectionId = sectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_comment.section_title
     *
     * @return the value of t_course_comment.section_title
     *
     * @mbg.generated Tue Aug 14 20:19:50 CST 2018
     */
    public String getSectionTitle() {
        return sectionTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_comment.section_title
     *
     * @param sectionTitle the value for t_course_comment.section_title
     *
     * @mbg.generated Tue Aug 14 20:19:50 CST 2018
     */
    public void setSectionTitle(String sectionTitle) {
        this.sectionTitle = sectionTitle == null ? null : sectionTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_comment.content
     *
     * @return the value of t_course_comment.content
     *
     * @mbg.generated Tue Aug 14 20:19:50 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_comment.content
     *
     * @param content the value for t_course_comment.content
     *
     * @mbg.generated Tue Aug 14 20:19:50 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_comment.create_time
     *
     * @return the value of t_course_comment.create_time
     *
     * @mbg.generated Tue Aug 14 20:19:50 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_comment.create_time
     *
     * @param createTime the value for t_course_comment.create_time
     *
     * @mbg.generated Tue Aug 14 20:19:50 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}