package com.xh.entity;

public class T_course_image {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_image.id
     *
     * @mbg.generated Sun Aug 26 22:03:04 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_image.filename
     *
     * @mbg.generated Sun Aug 26 22:03:04 CST 2018
     */
    private String filename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_image.id
     *
     * @return the value of t_course_image.id
     *
     * @mbg.generated Sun Aug 26 22:03:04 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_image.id
     *
     * @param id the value for t_course_image.id
     *
     * @mbg.generated Sun Aug 26 22:03:04 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_image.filename
     *
     * @return the value of t_course_image.filename
     *
     * @mbg.generated Sun Aug 26 22:03:04 CST 2018
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_image.filename
     *
     * @param filename the value for t_course_image.filename
     *
     * @mbg.generated Sun Aug 26 22:03:04 CST 2018
     */
    public void setFilename(String filename) {
        this.filename = filename == null ? null : filename.trim();
    }

    public T_course_image() {
    }

    @Override
    public String toString() {
        return "T_course_image{" +
                "id=" + id +
                ", filename='" + filename + '\'' +
                '}';
    }
}