package com.xh.entity;

public class T_site_carousel {
    //
    private Integer id;

    //名称
    private String name;

    //图片URL
    private String picture;

    //链接URL
    private String url;

    //权重
    private Integer weight;

    @Override
    public String toString() {
        return "T_site_carousel{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", picture='" + picture + '\'' +
                ", url='" + url + '\'' +
                ", weight=" + weight +
                '}';
    }

    //
    public Integer getId() {
        return id;
    }

    //
    public void setId(Integer id) {
        this.id = id;
    }

    //
    public String getName() {
        return name;
    }

    //
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_site_carousel.picture
     *
     * @return the value of t_site_carousel.picture
     *
     * @mbg.generated Tue Aug 14 20:19:50 CST 2018
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_site_carousel.picture
     *
     * @param picture the value for t_site_carousel.picture
     *
     * @mbg.generated Tue Aug 14 20:19:50 CST 2018
     */
    public void setPicture(String picture) {
        this.picture = picture == null ? null : picture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_site_carousel.url
     *
     * @return the value of t_site_carousel.url
     *
     * @mbg.generated Tue Aug 14 20:19:50 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_site_carousel.url
     *
     * @param url the value for t_site_carousel.url
     *
     * @mbg.generated Tue Aug 14 20:19:50 CST 2018
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_site_carousel.weight
     *
     * @return the value of t_site_carousel.weight
     *
     * @mbg.generated Tue Aug 14 20:19:50 CST 2018
     */
    public Integer getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_site_carousel.weight
     *
     * @param weight the value for t_site_carousel.weight
     *
     * @mbg.generated Tue Aug 14 20:19:50 CST 2018
     */
    public void setWeight(Integer weight) {
        this.weight = weight;
    }
}