package com.xh.entity;

import java.util.Date;
//用户收藏表
public class T_user_collections {
    //
    private Integer id;

    //用户id
    private Integer userId;

    //收藏课程id
    private Integer courseId;

    //收藏时间
    private Date createTime;

    //收藏课程名称
    private String courseName;

    //

    @Override
    public String toString() {
        return "T_user_collections{" +
                "id=" + id +
                ", userId=" + userId +
                ", courseId=" + courseId +
                ", createTime=" + createTime +
                ", courseName='" + courseName + '\'' +
                '}';
    }

    public Integer getId() {
        return id;
    }

    //
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_collections.user_id
     *
     * @return the value of t_user_collections.user_id
     *
     * @mbg.generated Tue Aug 14 20:19:50 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_collections.user_id
     *
     * @param userId the value for t_user_collections.user_id
     *
     * @mbg.generated Tue Aug 14 20:19:50 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_collections.course_id
     *
     * @return the value of t_user_collections.course_id
     *
     * @mbg.generated Tue Aug 14 20:19:50 CST 2018
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_collections.course_id
     *
     * @param courseId the value for t_user_collections.course_id
     *
     * @mbg.generated Tue Aug 14 20:19:50 CST 2018
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_collections.create_time
     *
     * @return the value of t_user_collections.create_time
     *
     * @mbg.generated Tue Aug 14 20:19:50 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_collections.create_time
     *
     * @param createTime the value for t_user_collections.create_time
     *
     * @mbg.generated Tue Aug 14 20:19:50 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_collections.course_name
     *
     * @return the value of t_user_collections.course_name
     *
     * @mbg.generated Tue Aug 14 20:19:50 CST 2018
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_collections.course_name
     *
     * @param courseName the value for t_user_collections.course_name
     *
     * @mbg.generated Tue Aug 14 20:19:50 CST 2018
     */
    public void setCourseName(String courseName) {
        this.courseName = courseName == null ? null : courseName.trim();
    }
}