package com.xh.entity;

import java.util.Date;
//用户学习表，记录用户所学的课程及其课程章节
public class T_user_course_section {
    //
    private Integer id;

    //用户id
    private Integer userId;

    //课程id
    private Integer courseId;

    //章节id
    private Integer sectionId;

    //状态：0-学习中；1-学习结束
    private Integer status;

    //学习进度
    private Integer rate;

    //更新时间
    private Date updateTime;

    //创建时间
    private Date createTime;

    //
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_course_section.id
     *
     * @param id the value for t_user_course_section.id
     *
     * @mbg.generated Tue Aug 14 20:19:50 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_course_section.user_id
     *
     * @return the value of t_user_course_section.user_id
     *
     * @mbg.generated Tue Aug 14 20:19:50 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_course_section.user_id
     *
     * @param userId the value for t_user_course_section.user_id
     *
     * @mbg.generated Tue Aug 14 20:19:50 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_course_section.course_id
     *
     * @return the value of t_user_course_section.course_id
     *
     * @mbg.generated Tue Aug 14 20:19:50 CST 2018
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_course_section.course_id
     *
     * @param courseId the value for t_user_course_section.course_id
     *
     * @mbg.generated Tue Aug 14 20:19:50 CST 2018
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_course_section.section_id
     *
     * @return the value of t_user_course_section.section_id
     *
     * @mbg.generated Tue Aug 14 20:19:50 CST 2018
     */
    public Integer getSectionId() {
        return sectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_course_section.section_id
     *
     * @param sectionId the value for t_user_course_section.section_id
     *
     * @mbg.generated Tue Aug 14 20:19:50 CST 2018
     */
    public void setSectionId(Integer sectionId) {
        this.sectionId = sectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_course_section.status
     *
     * @return the value of t_user_course_section.status
     *
     * @mbg.generated Tue Aug 14 20:19:50 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_course_section.status
     *
     * @param status the value for t_user_course_section.status
     *
     * @mbg.generated Tue Aug 14 20:19:50 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_course_section.rate
     *
     * @return the value of t_user_course_section.rate
     *
     * @mbg.generated Tue Aug 14 20:19:50 CST 2018
     */
    public Integer getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_course_section.rate
     *
     * @param rate the value for t_user_course_section.rate
     *
     * @mbg.generated Tue Aug 14 20:19:50 CST 2018
     */
    public void setRate(Integer rate) {
        this.rate = rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_course_section.update_time
     *
     * @return the value of t_user_course_section.update_time
     *
     * @mbg.generated Tue Aug 14 20:19:50 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_course_section.update_time
     *
     * @param updateTime the value for t_user_course_section.update_time
     *
     * @mbg.generated Tue Aug 14 20:19:50 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_course_section.create_time
     *
     * @return the value of t_user_course_section.create_time
     *
     * @mbg.generated Tue Aug 14 20:19:50 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_course_section.create_time
     *
     * @param createTime the value for t_user_course_section.create_time
     *
     * @mbg.generated Tue Aug 14 20:19:50 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}