package com.xh.entity;

public class T_user {
    //
    private Integer id;

    //用户名
    private String username;

    //密码
    private String password;

    //性别: 0-女；1-男
    private Integer gender;

    //头像
    private String header;

    //手机号码
    private String phone;

    //学历：大专及其以下、本科、硕士、博士、博士后
    private String education;

    //大学名称
    private String collegeName;

    //头衔
    private String title;

    //签名
    private String sign;

    //所在省份
    private String province;

    //所在城市
    private String city;

    //权重
    private Integer weight;

    public T_user() {
    }

    @Override
    public String toString() {
        return "T_user{" +
                "id=" + id +
                ", username='" + username + '\'' +
                ", password='" + password + '\'' +
                ", gender=" + gender +
                ", header='" + header + '\'' +
                ", phone='" + phone + '\'' +
                ", education='" + education + '\'' +
                ", collegeName='" + collegeName + '\'' +
                ", title='" + title + '\'' +
                ", sign='" + sign + '\'' +
                ", province='" + province + '\'' +
                ", city='" + city + '\'' +
                ", weight=" + weight +
                '}';
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.id
     *
     * @return the value of t_user.id
     *
     * @mbg.generated Tue Aug 14 20:19:50 CST 2018
     */

    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.id
     *
     * @param id the value for t_user.id
     *
     * @mbg.generated Tue Aug 14 20:19:50 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.username
     *
     * @return the value of t_user.username
     *
     * @mbg.generated Tue Aug 14 20:19:50 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.username
     *
     * @param username the value for t_user.username
     *
     * @mbg.generated Tue Aug 14 20:19:50 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.password
     *
     * @return the value of t_user.password
     *
     * @mbg.generated Tue Aug 14 20:19:50 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.password
     *
     * @param password the value for t_user.password
     *
     * @mbg.generated Tue Aug 14 20:19:50 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.gender
     *
     * @return the value of t_user.gender
     *
     * @mbg.generated Tue Aug 14 20:19:50 CST 2018
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.gender
     *
     * @param gender the value for t_user.gender
     *
     * @mbg.generated Tue Aug 14 20:19:50 CST 2018
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.header
     *
     * @return the value of t_user.header
     *
     * @mbg.generated Tue Aug 14 20:19:50 CST 2018
     */
    public String getHeader() {
        return header;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.header
     *
     * @param header the value for t_user.header
     *
     * @mbg.generated Tue Aug 14 20:19:50 CST 2018
     */
    public void setHeader(String header) {
        this.header = header == null ? null : header.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.phone
     *
     * @return the value of t_user.phone
     *
     * @mbg.generated Tue Aug 14 20:19:50 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.phone
     *
     * @param phone the value for t_user.phone
     *
     * @mbg.generated Tue Aug 14 20:19:50 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.education
     *
     * @return the value of t_user.education
     *
     * @mbg.generated Tue Aug 14 20:19:50 CST 2018
     */
    public String getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.education
     *
     * @param education the value for t_user.education
     *
     * @mbg.generated Tue Aug 14 20:19:50 CST 2018
     */
    public void setEducation(String education) {
        this.education = education == null ? null : education.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.college_name
     *
     * @return the value of t_user.college_name
     *
     * @mbg.generated Tue Aug 14 20:19:50 CST 2018
     */
    public String getCollegeName() {
        return collegeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.college_name
     *
     * @param collegeName the value for t_user.college_name
     *
     * @mbg.generated Tue Aug 14 20:19:50 CST 2018
     */
    public void setCollegeName(String collegeName) {
        this.collegeName = collegeName == null ? null : collegeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.title
     *
     * @return the value of t_user.title
     *
     * @mbg.generated Tue Aug 14 20:19:50 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.title
     *
     * @param title the value for t_user.title
     *
     * @mbg.generated Tue Aug 14 20:19:50 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.sign
     *
     * @return the value of t_user.sign
     *
     * @mbg.generated Tue Aug 14 20:19:50 CST 2018
     */
    public String getSign() {
        return sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.sign
     *
     * @param sign the value for t_user.sign
     *
     * @mbg.generated Tue Aug 14 20:19:50 CST 2018
     */
    public void setSign(String sign) {
        this.sign = sign == null ? null : sign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.province
     *
     * @return the value of t_user.province
     *
     * @mbg.generated Tue Aug 14 20:19:50 CST 2018
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.province
     *
     * @param province the value for t_user.province
     *
     * @mbg.generated Tue Aug 14 20:19:50 CST 2018
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.city
     *
     * @return the value of t_user.city
     *
     * @mbg.generated Tue Aug 14 20:19:50 CST 2018
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.city
     *
     * @param city the value for t_user.city
     *
     * @mbg.generated Tue Aug 14 20:19:50 CST 2018
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.weight
     *
     * @return the value of t_user.weight
     *
     * @mbg.generated Tue Aug 14 20:19:50 CST 2018
     */
    public Integer getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.weight
     *
     * @param weight the value for t_user.weight
     *
     * @mbg.generated Tue Aug 14 20:19:50 CST 2018
     */
    public void setWeight(Integer weight) {
        this.weight = weight;
    }
}