package com.xh.dao;

import com.xh.entity.T_site_carousel;
import java.util.List;

public interface T_site_carouselMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_site_carousel
     *
     * @mbg.generated Wed Aug 15 20:15:46 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_site_carousel
     *
     * @mbg.generated Wed Aug 15 20:15:46 CST 2018
     */
    int insert(T_site_carousel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_site_carousel
     *
     * @mbg.generated Wed Aug 15 20:15:46 CST 2018
     */
    T_site_carousel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_site_carousel
     *
     * @mbg.generated Wed Aug 15 20:15:46 CST 2018
     */
    List<T_site_carousel> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_site_carousel
     *
     * @mbg.generated Wed Aug 15 20:15:46 CST 2018
     */
    int updateByPrimaryKey(T_site_carousel record);
}