package com.xh.dao;

import com.xh.entity.T_course;
import com.xh.entity.T_user;
import java.util.List;

public interface T_userMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Wed Aug 15 20:15:46 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Wed Aug 15 20:15:46 CST 2018
     */
    int insert(T_user record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Wed Aug 15 20:15:46 CST 2018
     */
    T_user selectByPrimaryKey(Integer id);

    T_user selectByusername(String username);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Wed Aug 15 20:15:46 CST 2018
     */
    List<T_user> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Wed Aug 15 20:15:46 CST 2018
     */
    int updateByPrimaryKey(T_user record);
    int updatepwd(T_user user);
}