package com.xh.dao;

import com.xh.entity.T_user_collections;
import java.util.List;

public interface T_user_collectionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_collections
     *
     * @mbg.generated Wed Aug 15 20:15:46 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_collections
     *
     * @mbg.generated Wed Aug 15 20:15:46 CST 2018
     */
    int insert(T_user_collections record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_collections
     *
     * @mbg.generated Wed Aug 15 20:15:46 CST 2018
     */
    T_user_collections selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_collections
     *
     * @mbg.generated Wed Aug 15 20:15:46 CST 2018
     */
    List<T_user_collections> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_collections
     *
     * @mbg.generated Wed Aug 15 20:15:46 CST 2018
     */
    int updateByPrimaryKey(T_user_collections record);
}